-- Animals and pelts that can be stored in hunting wagons.
-- model = { name, big = large animal (takes 2 spots) }
Config.Animals = {
    a_c_alligator_01 = { "Alligator", big = true },
    a_c_alligator_03 = { "Alligator", big = true },
    a_c_armadillo_01 = { "Armadillo" },
    a_c_badger_01 = { "Badger" },
    a_c_bat_01 = { "Bat" },
    a_c_bear_01 = { "Bear", big = true },
    a_c_bearblack_01 = { "Black Bear", big = true },
    a_c_beaver_01 = { "Beaver", big = true },
    a_c_bighornram_01 = { "Bighorn Ram", big = true },
    a_c_boar_01 = { "Boar", big = true },
    a_c_buck_01 = { "Deer", big = true },
    a_c_buffalo_01 = { "Bison", big = true },
    a_c_bull_01 = { "Bull", big = true },
    a_c_californiacondor_01 = { "California Condor" },
    a_c_cardinal_01 = { "Cardinal" },
    a_c_carolinaparakeet_01 = { "Carolina Parakeet" },
    a_c_cedarwaxwing_01 = { "Cedar Waxwing" },
    a_c_chicken_01 = { "Chicken" },
    a_c_chipmunk_01 = { "Chipmunk" },
    a_c_cormorant_01 = { "Cormorant" },
    a_c_cougar_01 = { "Cougar", big = true },
    a_c_cow = { "Cow", big = true },
    a_c_coyote_01 = { "Coyote", big = true },
    a_c_crab_01 = { "Crab" },
    a_c_cranewhooping_01 = { "Whooping Crane" },
    a_c_crow_01 = { "Crow" },
    a_c_deer_01 = { "Deer", big = true },
    a_c_duck_01 = { "Duck" },
    a_c_eagle_01 = { "Eagle" },
    a_c_egret_01 = { "Heron" },
    a_c_elk_01 = { "Moose", big = true },
    a_c_fishchannelcatfish_01_lg = { "Catfish", big = true },
    a_c_fishlakesturgeon_01_lg = { "Sturgeon", big = true },
    a_c_fishlongnosegar_01_lg = { "Longnose Gar", big = true },
    a_c_fishmuskie_01_lg = { "Muskie", big = true },
    a_c_fishnorthernpike_01_lg = { "Pike", big = true },
    a_c_fox_01 = { "Fox", big = true },
    a_c_frogbull_01 = { "Bullfrog" },
    a_c_gilamonster_01 = { "Gila Monster" },
    a_c_goat_01 = { "Goat", big = true },
    a_c_goosecanada_01 = { "Canada Goose" },
    a_c_hawk_01 = { "Hawk" },
    a_c_heron_01 = { "Heron" },
    a_c_iguana_01 = { "Iguana" },
    a_c_iguanadesert_01 = { "Desert Iguana" },
    a_c_javelina_01 = { "Peccary", big = true },
    a_c_loon_01 = { "Loon" },
    a_c_moose_01 = { "Moose", big = true },
    a_c_muskrat_01 = { "Muskrat" },
    a_c_oriole_01 = { "Oriole" },
    a_c_owl_01 = { "Owl" },
    a_c_ox_01 = { "Ox", big = true },
    a_c_panther_01 = { "Panther", big = true },
    a_c_parrot_01 = { "Parrot" },
    a_c_pelican_01 = { "Pelican" },
    a_c_pheasant_01 = { "Pheasant" },
    a_c_pig_01 = { "Pig", big = true },
    a_c_pigeon = { "Pigeon" },
    a_c_possum_01 = { "Opossum" },
    a_c_prairiechicken_01 = { "Prairie Chicken" },
    a_c_pronghorn_01 = { "Pronghorn", big = true },
    a_c_quail_01 = { "Quail" },
    a_c_rabbit_01 = { "Rabbit" },
    a_c_raccoon_01 = { "Raccoon" },
    a_c_rat_01 = { "Rat" },
    a_c_raven_01 = { "Crow" },
    a_c_redfootedbooby_01 = { "Booby" },
    a_c_robin_01 = { "Robin" },
    a_c_rooster_01 = { "Rooster" },
    a_c_roseatespoonbill_01 = { "Spoonbill" },
    a_c_seagull_01 = { "Seagull" },
    a_c_sheep_01 = { "Sheep", big = true },
    a_c_skunk_01 = { "Opossum" },
    a_c_snake_01 = { "Snake" },
    a_c_snakeblacktailrattle_01 = { "Rattlesnake" },
    a_c_snakeferdelance_01 = { "Copperhead" },
    a_c_snakewater_01 = { "Water Snake" },
    a_c_songbird_01 = { "Bird" },
    a_c_sparrow_01 = { "Sparrow" },
    a_c_squirrel_01 = { "Squirrel" },
    a_c_toad_01 = { "Toad" },
    a_c_turkey_01 = { "Turkey" },
    a_c_turkeywild_01 = { "Wild Turkey" },
    a_c_turtlesnapping_01 = { "Turtle" },
    a_c_vulture_01 = { "Vulture" },
    a_c_wolf = { "Wolf", big = true },
    a_c_wolf_medium = { "Medium Wolf", big = true },
    a_c_wolf_small = { "Small Wolf", big = true },
    a_c_woodpecker_01 = { "Woodpecker" },
    a_c_woodpecker_02 = { "Woodpecker" },
    mp_a_c_alligator_01 = { "Alligator", big = true },
    mp_a_c_beaver_01 = { "Beaver", big = true },
    mp_a_c_bighornram_01 = { "Bighorn Ram", big = true },
    mp_a_c_boar_01 = { "Boar", big = true },
    mp_a_c_buck_01 = { "Deer", big = true },
    mp_a_c_chicken_01 = { "Chicken" },
    mp_a_c_cougar_01 = { "Cougar" },
    mp_a_c_coyote_01 = { "Legendary Coyote" },
    mp_a_c_fox_01 = { "Legendary Fox" },
    mp_a_c_panther_01 = { "Legendary Panther" },
    mp_a_c_wolf_01 = { "Legendary Wolf" },
}

-- Pelts (objects carried after skinning)
Config.Pelts = {
    mp007_p_nat_pelt_buffalolegend01x = { "Pelt", big = true },
    mp007_p_nat_pelt_gatorlegend01x = { "Pelt", big = true },
    p_bespokemoosexlpelt01x = { "Pelt", big = true },
    p_cs_alligatorpelt_large = { "Pelt", big = true },
    p_cs_blackbearskin_medlarge = { "Pelt", big = true },
    p_cs_cowpelt2_xlarge = { "Pelt", big = true },
    p_cs_gilamonsterpelt01x = { "Pelt" },
    p_cs_iguanapelt = { "Pelt" },
    p_cs_iguanapelt02x = { "Pelt" },
    p_cs_medium = { "Pelt" },
    p_cs_medium_og = { "Pelt" },
    p_cs_medlarge = { "Pelt" },
    p_cs_pelt_elklegendary = { "Pelt", big = true },
    p_cs_pelt_large = { "Pelt" },
    p_cs_pelt_med_armadillo = { "Pelt" },
    p_cs_pelt_med_badger = { "Pelt" },
    p_cs_pelt_med_muskrat = { "Pelt" },
    p_cs_pelt_med_possum = { "Pelt" },
    p_cs_pelt_med_raccoon = { "Pelt" },
    p_cs_pelt_med_skunk = { "Pelt" },
    p_cs_pelt_medlarge = { "Pelt" },
    p_cs_pelt_xlarge = { "Pelt", big = true },
    p_cs_pelt_xlarge_alligator = { "Pelt", big = true },
    p_cs_pelt_xlarge_bear = { "Pelt", big = true },
    p_cs_pelt_xlarge_bearlegendary = { "Pelt", big = true },
    p_cs_pelt_xlarge_buffalo = { "Pelt", big = true },
    p_cs_pelt_xlarge_elk = { "Pelt", big = true },
    p_cs_pelt_xlarge_tbuffalo = { "Pelt", big = true },
    p_cs_pelt_xlarge_wbuffalo = { "Pelt", big = true },
    p_cs_wolf = { "Pelt" },
    p_cs_wolf_roll = { "Pelt" },
    p_cs_wolfpelt_large = { "Pelt" },
    p_cs_ws_alligator = { "Pelt", big = true },
}

-- Store pelts as well as carcasses?
Config.StorePelts = true
