-- Wagon catalogue: categories, wagons for sale and per-model customisation.
--[[
    Fields per wagon:
      model, label, enabled, cash, gold, resale (%), storage (storage capacity),
      animals (carcasses/pelts it carries), big (big wagon: spawns further away),
      jobs/groups (purchase restriction), work ('wood' | 'stone' | 'water' -> work wagon), description
]]
Config.Wagons = {
    {
        category = "Hunting Wagons",
        icon = "hunt",
        wagons = {
            { model = "wagon05x", label = "Hunting Wagon 1", enabled = true, cash = 2500, gold = 0, resale = 4, storage = 500, animals = 50, big = true, description = "A good wagon for hunting and storage." },
            { model = "cart04", label = "Hunting Wagon 2", enabled = true, cash = 1600, gold = 0, resale = 4, storage = 200, animals = 40, description = "A good wagon for hunting and storage." },
            { model = "cart03", label = "Small Hunting Wagon 1", enabled = true, cash = 650, gold = 0, resale = 4, storage = 110, animals = 20, description = "A good wagon for hunting and storage." },
            { model = "cart07", label = "Small Hunting Wagon 2", enabled = true, cash = 900, gold = 0, resale = 4, storage = 150, animals = 30, description = "A good wagon for hunting and storage." },
            { model = "cart08", label = "Small Hunting Wagon 3", enabled = true, cash = 1200, gold = 0, resale = 4, storage = 190, animals = 30, description = "A good wagon for hunting and storage." },
            { model = "wagon02x", label = "Cargo Wagon 2", enabled = true, cash = 2000, gold = 0, resale = 4, storage = 380, animals = 40, big = true, description = "A good wagon for hunting and storage." },
            { model = "chuckwagon002x", label = "Cargo Wagon 3", enabled = true, cash = 2500, gold = 0, resale = 4, storage = 430, animals = 50, big = true, description = "A good wagon for hunting and storage." },
            { model = "chuckwagon000x", label = "Cargo Wagon 4", enabled = true, cash = 2750, gold = 0, resale = 4, storage = 470, animals = 40, big = true, description = "A good wagon for hunting and storage." },
            { model = "gatchuck", label = "Cargo Wagon 5", enabled = true, cash = 1950, gold = 0, resale = 4, storage = 250, animals = 30, big = true, description = "A good wagon for hunting and storage." },
            { model = "utilliwag", label = "Cargo Wagon 6", enabled = true, cash = 2300, gold = 0, resale = 4, storage = 380, animals = 40, big = true, description = "A good wagon for hunting and storage." },
            { model = "huntercart01", label = "Hunting Wagon 3", enabled = true, cash = 1500, gold = 0, resale = 4, storage = 220, animals = 30, big = true, description = "A good wagon for hunting and storage." },
            { model = "wagon04x", label = "Hunting Wagon 4", enabled = true, cash = 3000, gold = 0, resale = 4, storage = 400, animals = 50, big = true, description = "A good wagon for hunting and storage." },
            { model = "supplywagon", label = "Cargo Wagon 7", enabled = true, cash = 4500, gold = 0, resale = 4, storage = 700, animals = 80, big = true, description = "A good wagon for hunting and storage." },
        },
    },
    {
        category = "Work Wagons",
        icon = "work",
        wagons = {
            { model = "coal_wagon", label = "Stone Wagon", enabled = true, cash = 1000, gold = 0, resale = 4, storage = 500, animals = 0, work = "stone", description = "A good wagon for work and storage." },
            { model = "oilWagon01x", label = "Water Tank", enabled = true, cash = 1000, gold = 0, resale = 4, storage = 150, animals = 0, work = "water", description = "A good wagon for work and storage." },
            { model = "wagonPrison01x", label = "Prison Wagon", enabled = true, cash = 0, gold = 20, resale = 4, storage = 0, animals = 0, description = "A good wagon for police work." },
            { model = "logwagon", label = "Lumber Wagon", enabled = true, cash = 1000, gold = 0, resale = 4, storage = 500, animals = 0, work = "wood", description = "A good wagon for work and storage." },
        },
    },
    {
        category = "Passenger Wagons",
        icon = "travel",
        wagons = {
            { model = "buggy01", label = "Buggy 1", enabled = true, cash = 700, gold = 0, resale = 4, storage = 100, animals = 0, description = "A good wagon for travelling and storage." },
            { model = "buggy02", label = "Buggy 3", enabled = true, cash = 850, gold = 0, resale = 4, storage = 120, animals = 0, description = "A good wagon for travelling and storage." },
            { model = "buggy03", label = "Buggy 4", enabled = true, cash = 1000, gold = 0, resale = 4, storage = 130, animals = 0, description = "A good wagon for travelling and storage." },
            { model = "cart01", label = "Cart 1", enabled = true, cash = 400, gold = 0, resale = 4, storage = 100, animals = 0, description = "A good wagon for travelling and storage." },
            { model = "cart02", label = "Cart 2", enabled = true, cash = 400, gold = 0, resale = 4, storage = 100, animals = 0, description = "A good wagon for travelling and storage." },
            { model = "wagon03x", label = "Large Wagon 1", enabled = true, cash = 3500, gold = 0, resale = 4, storage = 700, animals = 0, description = "A good wagon for travelling and storage." },
            { model = "wagon06x", label = "Large Wagon 2", enabled = true, cash = 2000, gold = 0, resale = 4, storage = 500, animals = 0, description = "A good wagon for travelling and storage." },
            { model = "coach2", label = "Cart 4", enabled = true, cash = 1200, gold = 0, resale = 4, storage = 300, animals = 0, description = "A good wagon for travelling and storage." },
            { model = "coach3", label = "Cart 5", enabled = true, cash = 1200, gold = 0, resale = 4, storage = 300, animals = 0, description = "A good wagon for travelling and storage." },
            { model = "coach4", label = "Cart 6", enabled = true, cash = 800, gold = 0, resale = 4, storage = 190, animals = 0, description = "A good wagon for travelling and storage." },
            { model = "coach5", label = "Cart 7", enabled = true, cash = 900, gold = 0, resale = 4, storage = 190, animals = 0, description = "A good wagon for travelling and storage." },
            { model = "coach6", label = "Cart 8", enabled = true, cash = 950, gold = 0, resale = 4, storage = 200, animals = 0, description = "A good wagon for travelling and storage." },
            { model = "stagecoach001x", label = "Cart 9", enabled = true, cash = 1400, gold = 0, resale = 4, storage = 290, animals = 0, description = "A good wagon for travelling and storage." },
            { model = "stagecoach002x", label = "Cart 10", enabled = true, cash = 1400, gold = 0, resale = 4, storage = 290, animals = 0, description = "A good wagon for travelling and storage." },
            { model = "stagecoach003x", label = "Cart 11", enabled = true, cash = 900, gold = 0, resale = 4, storage = 180, animals = 0, description = "A good wagon for travelling and storage." },
            { model = "stagecoach005x", label = "Cart 12", enabled = true, cash = 1150, gold = 0, resale = 4, storage = 250, animals = 0, description = "A good wagon for travelling and storage." },
            { model = "stagecoach006x", label = "Cart 13", enabled = true, cash = 2500, gold = 0, resale = 4, storage = 500, animals = 0, description = "A good wagon for travelling and storage." },
            { model = "wagondairy01x", label = "Supply Cart", enabled = true, cash = 900, gold = 0, resale = 4, storage = 150, animals = 0, description = "A good wagon for travelling and storage." },
            { model = "wagondoc01x", label = "Doctor's Wagon", enabled = true, cash = 0, gold = 1, resale = 4, storage = 1200, animals = 0, jobs = { "doctor" }, description = "A good wagon for travelling and storage." },
            { model = "wagontraveller01x", label = "Travel Wagon 1", enabled = true, cash = 900, gold = 0, resale = 4, storage = 150, animals = 0, description = "A good wagon for travelling and storage." },
            { model = "wagonwork01x", label = "Travel Wagon 2", enabled = true, cash = 900, gold = 0, resale = 4, storage = 150, animals = 0, description = "A good wagon for travelling and storage." },
            { model = "stagecoach004_2x", label = "Armoured Wagon", enabled = true, cash = 15000, gold = 0, resale = 4, storage = 1200, animals = 0, description = "A good wagon for travelling and storage." },
        },
    },
    {
        category = "Special",
        icon = "vip",
        wagons = {
            { model = "stagecoach004x", label = "Special Armoured Wagon", enabled = true, cash = 0, gold = 30, resale = 4, storage = 1800, animals = 0, description = "A good wagon for travelling and storage." },
            { model = "bountywagon01x", label = "Armoured Hunting Wagon", enabled = true, cash = 0, gold = 35, resale = 4, storage = 2000, animals = 150, description = "A good wagon for hunting and storage." },
        },
    },
}

-- Customisation per model (lowercase keys)
Config.WagonCustom = {
    liveries = {
        privatebaggage01x = { "LM", "CU", "SE", "PU" },
        gatchuck = { "0 - Simple Red Yellow", "1 - Tapered Yellow Cream", "2 - Squared Gold Black", "3 - Flourish Gold Cream", "4 - Simple Cream", "5 - Tapered Gold Red", "6 - Squared Cream Red", "7 - Flourish Black Yellow", "8 - Simple Yellow Red", "9 - Tapered Gold Black", "10 - Squared Black Red", "11 - Flourish Cream Gold", "12 - Gold Cream", "13 - Tapered Blue Black", "14 - Squared Gold Black", "15 - Flourish Yellow Red" },
        privateboxcar04x = { "0 -Lannahechee", "1 -Central Union", "2 -Southern and Eastern", "ARMY", "PU" },
        privateboxcar02x = { "0 -LM", "01 -CU", "02 -SE", "03 -military", "PU" },
        stagecoach002x = { "0 -Davis", "1 -Boles", "2 -Heartlands", "3 -Tapered" },
        cart03 = { "0 - Simple Cream", "1 - Tapered Double Cream Yellow", "2 - Loco Red Yellow", "3 - Fancy Red Blue Yellow", "4 - Simple Worn Yellow Cream", "5 - Chassis Worn Cream", "6 - Loco Red Black", "7 - Loco Blue Cream", "8 - Fancy Red Gold", "9 - Tapered Double Red Yellow" },
        midlandboxcar05x = { "LM", "CU", "SE", "PU" },
        midlandrefrigeratorcar = { "LM" },
        boatsteam02x = { "0 -AnnieMay", "1 -Calliope", "2 -LaChuparrosa", "3 -Magicienne" },
        northpassenger03x = { "CU" },
        privateopensleeper01x = { "SE", "ARMY", "PU" },
        coach4 = { "0 - Lines Red Grey", "1 - Crosshatch Red Green", "2 - Accented Red Yellow", "3 - Leaf Yellow", "4 - Lines Red Green", "5 - Crosshatch Red Yellow", "6 - Accented Gold Red", "7 - Leaf Red Yellow", "8 - Lines Yellow Orange", "9 - Crosshatch Cream", "10 - Crosshatch Green", "11 - Leaf Gold", "12 - Lines Gold Yellow", "13 - Crosshatch Gold" },
        wagon05x = { "0 - Simple Yellow", "1 - Tapered Gold", "2 - Double Cream Orange", "3 - Flourish Yellow Orange", "4 - Simple Cream", "5 - Tapered Orange", "6 - Double Cream Red", "7 - Flourish Yellow Red", "8 - Simple Red", "9 - Tapered Yellow", "10 - Double Creams", "11 - Flourish Black Gold", "12 - Simple Red", "13 - Tapered Green", "14 - Double Yellow Cream", "15 - Flourish Yellow Cream", "16 - Simple Orange", "17 - Tapered Black", "18 - Double Black Red", "19 - Flourish Worn Red Cream" },
        bountywagon01x = { "0 - Livery1", "1 - Livery2", "2 - Livery3" },
        policewagon01x = { "0 - Police Red White" },
        stagecoach003x = { "1 -Davis", "2 -Boles", "3 -Heartlands", "4 -Ornate" },
        coach5 = { "0 - Lines Yellow", "1 - Tapered Yellow", "2 - Squared Yellow Cream", "3 - Leaf Yellow", "4 - Lines Red Yellow", "5 - Tapered Red Yellow", "6 - Squared Red Yellow", "7 - Leaf Red Yellow", "8 - Lines Gold", "9 - Tapered Gold", "10 - Squared Gold", "11 - Leaf Gold" },
        coach6 = { "0 - Simple Cream", "1 - Tapered Cream", "2 - Squared Cream", "3 - Leaf Cream Yellow", "4 - Simple Yellow", "5 - Tapered Yellow Red", "6 - Squared Yellow", "7 - Leaf Red Yellow", "8 - Simple Red Yellow", "9 - Tapered Red Yellow", "10 - Squared Red", "11 - Leaf Black Yellow", "12 - Simple Black", "13 - Tapered Gold Black", "14 - Squared", "15 - Leaf Gold" },
        northcoalcar01x = { "CU", "LM" },
        policewagongatling01x = { "0 - Police Red White" },
        privateboxcar01x = { "LM", "CU", "SE", "ARMY", "PU" },
        chuckwagon002x = { "0 - Simple Lining Yellow", "1 - Double Lining Red Black", "2 - Loco Grey Red", "3 - Flourish Red Yellow", "4 - Simple Lining Cream Red", "5 - Double Lining Red Yellow", "6 - Loco Red Cream", "7 - Flourish Green", "8 - Simple Lining Cream", "9 - Double Lining Gold Red", "10 - Gold Leaf" },
        coach3_cutscene = { "1 -Lines", "2 -Flourish", "3 -Gold Tapered", "4 -Gold Leaf" },
        privatedining01x = { "SE", "PU" },
        privatesteamer01x = { "SE", "PU" },
        coach3 = { "0 - Lines Gold", "1 - Flourish Yellow", "2 - Tapered Yellow", "3 -  Leaf Yellow Red", "4 - Lines Blue", "5 - Flourish Gold Red", "6 - Tapered Blue Grey", "7 - Leaf Gold", "8 - Lines Orange", "9 - Flourish Red Cream", "10 - Tapered Orange Yellow", "11 - Leaf Worn", "12 - Tapered Red Orange" },
        coach2 = { "0 -Davis", "1 -Boles", "2 -Heartlands", "3 -Tapered" },
        huntercart01 = { "0 - Hunt0", "1 - Hunt1", "2 - Hunt2", "3 - Hunt3", "4 - Hunt4", "5 - Hunt5" },
        oilwagon01x = { "0 - Cornwall Red Cream", "1 - Cornwall Red Black", "2 - Cornwall Cream Yellow", "3 - Cornwall Cream Red Yellow", "4 - Cornwall White Orange", "5 -  Cornwall Yellow Red" },
        wagon06x = { "0 - Simple Cream Red", "1 - Double Red Yellow", "2 - Flourish Cream Gold", "3 - Flourish II Red Black Yellow", "4 - Simple Red", "5 - Double Cream Yellow", "6 - Flourish Black Yellow", "7 - Flourish II Black Cream Gold", "8 - Simple Red", "9 - Double Red Cream", "10 - Flourish Black Gold", "11 - Flourish II Cream Orange Yellow", "12 - Simple Yellow Red", "13 - Double Black Red", "14 - Flourish Red Yellow", "15 - Flourish II Green Gold" },
        wagon03x = { "0 - Simple Brown Red", "1 - Double Red Yellow", "2 - Tapered Yellow Red", "3 - Flourish Gold Black", "4 - Simple Red", "5 - Double Yellow Red", "6 - Tapered Cream Red", "7 - Flourish Red Black", "8 - Simple Black", "9 - Double Lining", "10 - Tapered Yellow", "11 - Flourish Red Gold", "12 - Simple Brown", "13 - Double Red", "14 - Tapered Cream Red", "15 - Flourish Red Yellow" },
        cart02 = { "0 - Tapered Double Red Yellow", "1 - Crossed Yellow Grey", "2 - Leaf Yellow", "3 - Flourish Red Yellow", "4 - Tapered Worn Grey Yellow", "5 - Simple Worn Cream", "6 - Leaf Gold", "7 - Flourish Gold", "8 - Tapered Double Red Grey", "9 - Crossed Red Yellow", "10 - Leaf Red Yellow", "11 - Flourish Brown", "12 - Tapered Worn Red Yellow", "13 - Simple Worn Yellow", "14 - Leaf Cream Red", "15 - Flourish Yellow" },
        warwagon2 = { "0 -Simple Lining", "1 -Double Lining", "2 -Tapered", "3 -Gold Leaf" },
        wagonarmoured01x = { "0 - Liv 1", "1 - Liv 1a", "2 - Liv 1b", "3 -Liv 2", "4 -Liv 2a", "5 -Liv 2b", "6 -Liv 3", "7 -Liv 3a", "8 -Liv 3b", "9 -Liv 4", "10 -Liv 4a", "11 -Liv 4b", "12 -Liv 5", "13 -Liv 5a", "14 -Liv 5b", "15 -Liv 6", "16 -Liv 6a", "17 -Liv 6b", "18 -Liv 7", "19 -Liv 7a", "20 -Liv 7b", "21 -Liv 8", "22 -Liv 8a", "23 -Liv 8b", "24 -Liv 9", "25 -Liv 9a", "26 -Liv 9b", "27 -Liv 10", "28 -Liv 10a", "29 -Liv 10b", "30 -Liv 10c" },
        caboose01x = { "LM", "CU", "SE", "PU" },
        stagecoach004_2x = { "0 -Davis", "1 -Boles", "2 -Heartland", "3 -Tapered", "4 -Lemoyne" },
        privatepassenger01x = { "SE", "PU" },
        trolley01x = { "CWALL", "PU" },
        northsteamer01x = { "northsteamer01x_LM", "northsteamer01x_CU" },
        northpassenger01x = { "CU" },
        utilliwag = { "0 - Simple Red", "1 - Double Red Cream", "2 - Tapered Yellow Cream", "3 - Flourish Cream Yellow", "4 - Simple Red Yellow", "5 - Double Red Black", "6 - Tapered Red Cream Black", "7 - Flourish Red Cream Gold", "8 - Simple Black", "9 - Double Red Black", "10 - Tapered Cream Red", "11 - Flourish Brown Gold", "12 - Simple Cream Yellow", "13 - Double Gold Cream", "14 - Tapered Yellow Blue", "15 - Flourish Red Yellow" },
        cart06 = { "-1 - Default", "0 - Simple Yellow White", "1 - Tapered Double Yellow Red", "2 - Ornate Yellow", "3 - Flourish Yellow Red", "4 - Chassis Line White Yellow", "5 - Rounded Blue White", "6 - Simple White Red", "7 - Tapered Double White Red", "8 - Ornate Light Green", "9 - Flourish Red", "10 - Chassis Line Yellow Red", "11 - Rounded Yellow Red", "12 - Tapered Double Black" },
        wagondoc01x = { "0 -Doctors" },
        coal_wagon = { "0 -M.Harris01", "1 -Jameson01", "2 -M.Harris02", "3 -Jameson02" },
        supplywagon2 = { "0 - Simple Yellow Blue", "1 - Double Yellow Red", "2 - Tapered Yellow Red", "3 - Flourish Green Yellow", "4 - Appleseed Timber", "5 - Simple Brown Blue", "6 - Double Lining Green Yellow", "7 - Tapered Yellow Cream", "8 - Flourish Red Yellow", "9 - Simple Red", "10 - Double Brown Cream", "11 - Tapered Gold Orange", "12 - Flourish Cream Blue", "13 - Double Gold Black", "14 - Tapered Cream Orange", "15 - Flourish Gold Brown" },
        cart04 = { "0 - Simple Yellow", "1 - Loco Cream Red", "2 - Tapered Double Red Yellow", "3 - Flourish Yellow", "4 - Lines Red Yellow", "5 - Lines Thick White Yellow", "6 - Flourish Gold" },
        supplywagon = { "0 - Simple Yellow Blue", "1 - Double Yellow Red", "2 - Tapered Yellow Red", "3 - Flourish Green Yellow", "4 - Appleseed Timber", "5 - Simple Brown Blue", "6 - Double Lining Green Yellow", "7 - Tapered Yellow Cream", "8 - Flourish Red Yellow", "9 - Simple Red", "10 - Double Brown Cream", "11 - Tapered Gold Orange", "12 - Flourish Cream Blue", "13 - Double Gold Black", "14 - Tapered Cream Orange", "15 - Flourish Gold Brown" },
        wagonwork01x = { "0 -Wakefield" },
        stagecoach004x = { "0 -Boles" },
        armysupplywagon = { "0 -US Army" },
        stagecoach006x = { "1 -Davis", "2 -Boles", "3 -Heartlands", "4 -Simple" },
        buggy02 = { "0 - Simple Yellow", "1 - Flourish Red Yellow", "2 - Ornate Red Yellow", "3 - Fancy Yellow Brown", "4 - Simple Red", "5 - Flourish Orange Red", "6 - Ornate Red Orange", "7 - Fancy Red Orange", "8 - Simple Cream", "9 - Flourish Gold", "10 - Ornate Gold Black", "11 - Fancy Gold", "12 - Simple Black", "13 - Flourish Red Black", "14 - Ornate Red Black" },
        wagon02x = { "0 - Simple Red", "1 - Double Cream Yellow", "2 - Tapered Red", "3 - Flourish Red Cream", "4 - Jameson", "5 - Cornwall", "6 - Simple Orange", "7 - Double Lining", "8 - Tapered Orange", "9 - Flourish Red Yellow", "10 - Simple Black", "11 - Double Cream Yellow", "12 - Tapered Cream Yellow", "13 - Flourish Gold", "14 - Simple Yellow", "15 - Double Red Yellow", "16 - Tapered Gold" },
        cart07 = { "0 - Simple Green Yellow", "1 - Tapered Double Yellow Red", "2 - Loco Black Red Yellow", "3 - Flourish Yellow Orange", "4 - Rounded Off-White Yellow", "5 - Rounded Worn Red Brown", "6 - Tapered Double Orange Yellow", "7 - Flourish Gold", "8 - Rounded Grey Orange", "9 - Loco Blue Black Yellow", "10 - Simple Red Yellow", "11 - Rounded Worn Black White" },
        privatecoalcar01x = { "SE", "PU", "ARMY" },
        oilwagon02x = { "0 - Cornwall Red Cream", "1 - Cornwall Red Black", "2 - Cornwall Cream Yellow", "3 - Cornwall Cream Red Yellow", "4 - Cornwall White Orange", "5 -  Cornwall Yellow Red" },
        handcart = { "0 " },
        buggy01 = { "0 - Simple Yellow", "1 - Flourish Red Yellow", "2 - Ornate Red Yellow", "3 - Fancy Yellow Brown", "4 - Simple Red", "5 - Flourish Orange Red", "6 - Ornate Red Orange", "7 - Fancy Red Orange", "8 - Simple Cream", "9 - Flourish Gold Cream", "10 - Ornate Gold Black", "11 - Fancy Gold", "12 - Simple Black", "13 - Flourish Red Black", "14 - Ornate Red Black" },
        buggy03 = { "0 - Simple Yellow", "1 - Flourish Red Yellow", "2 - Ornate Red Yellow", "3 - Fancy Yellow Brown", "4 - Simple Red", "5 - Flourish Orange Red", "6 - Ornate Red Orange", "7 - Fancy Red Orange", "8 - Simple Cream", "9 - Flourish Gold Cream", "10 - Ornate Gold Black", "11 - Fancy Gold", "12 - Simple Black", "13 - Flourish Red Black", "14 - Ornate Red Black" },
        wagontraveller01x = { "0 - Traveller Red Yellow" },
        cart05 = { "0 - Line Blue", "1 - Double Line Yellow", "2 - Line Thick Green", "3 - Flourish Red", "4 - Simple Red", "5 - Simple White", "6 - Line Thick Yellow Orange", "7 - Line Thick Red Blue", "8 - Flourish Yellow White", "9 - Double Line Orange" },
        gatchuck_2 = { "0 - Simple Red Yellow", "1 - Tapered Yellow Cream", "2 - Squared Gold Black", "3 - Flourish Gold Cream", "4 - Simple Cream", "5 - Tapered Gold Red", "6 - Squared Cream Red", "7 - Flourish Black Yellow", "8 - Simple Yellow Red", "9 - Tapered Gold Black", "10 - Squared Black Red", "11 - Flourish Cream Gold", "12 - Gold Cream", "13 - Tapered Blue Black", "14 - Squared Gold Black", "15 - Flourish Yellow Red" },
        cart08 = { "0 - Single Line Yellow Red", "1 - Simple Double Cream Yellow", "2 - Tapered Double Brown White", "3 - Flourish Cream", "4 - Simple Red", "5 - Chassis Cream Yellow", "6 - Single Line Orange", "7 - Double Line Brown", "8 - Single Line Brown Red", "9 - Simple Double Cream Yellow", "10 - Tapered Double Grey White", "11 - Flourish Gold", "12 - Simple Blue Red", "13 - Chassis Red Yellow", "14 - Single Line Bright Orange", "15 - Double Line Worn" },
        wagondairy01x = { "0 - Kauffman", "1 - Kauffman Worn" },
        wagon04x = { "0 - Simple Cream", "1 - Double Yellows", "2 - Tapered Red", "3 - Flourish Red Yellow", "4 - Simple Red", "5 - Double Yellow White", "6 - Tapered Yellow", "7 - Flourish Cream Black", "8 - Simple Green", "9 - Double Red Yellow", "10 - Tapered Cream", "11 - Flourish Black Gold", "12 - Simple Black Cream", "13 - Double Brown Orange", "14 - Tapered Orange", "15 - Flourish Cream Red" },
        stagecoach005x = { "1 -Davis", "2 -Boles", "3 -Heartlands", "4 -Tapered" },
        chuckwagon000x = { "0 -Simple Lining Red", "1 - Dot Lining Red Yellow", "2 - Double Lining White Blue", "3 - Flourish Yellow", "4 -Simple Lining Yellow", "5 - Dot Lining Orange Yellow", "6 - Double Lining Black Red", "7 - Flourish Red Yellow", "8 - Flourish Cream Gold", "9 - Flourish Red Black", "10 - Double Lining Red Yellow" },
        stagecoach001x = { "1 -Davis", "2 -Boles", "3 -Heartlands", "4 -Ornate" },
        privateopensleeper02x = { "SE", "ARMY", "PU" },
        privaterooms01x = { "SE", "PU" },
        cart01 = { "0 - Simple Cream", "1 - Tapered Double Yellow", "2 - Loco Cream Blue", "3 - Flourish Yellow Cream", "4 - Simple Worn Yellow", "5 - Tapered Worn Cream", "6 - Simple Yellow", "7 - Tapered Double Red Cream", "8 - Loco Cream Red", "9 - Flourish Red Yellow", "10 - Simple Worn Cream", "11 - Tapered Worn Red Cream" },
        wagon05x_2 = { "0 - Simple Yellow", "1 - Tapered Gold", "2 - Double Cream Orange", "3 - Flourish Yellow Orange", "4 - Simple Cream", "5 - Tapered Orange", "6 - Double Cream Red", "7 - Flourish Yellow Red", "8 - Simple Red", "9 - Tapered Yellow", "10 - Double Creams", "11 - Flourish Black Gold", "12 - Simple Red", "13 - Tapered Green", "14 - Double Yellow Cream", "15 - Flourish Yellow Cream", "16 - Simple Orange", "17 - Tapered Black", "18 - Double Black Red", "19 - Flourish Worn Red Cream" },
    },
    tints = {
        armoredcar01x = 1,
        armoredcar03x = 1,
        armysupplywagon = 1,
        boatsteam02x = 6,
        bountywagon01x = 5,
        buggy01 = 14,
        buggy02 = 16,
        buggy03 = 16,
        caboose01x = 12,
        canoe = 5,
        canoetreetrunk = 1,
        cart01 = 27,
        cart02 = 24,
        cart03 = 25,
        cart04 = 19,
        cart05 = 24,
        cart06 = 25,
        cart07 = 24,
        cart08 = 20,
        chuckwagon000x = 15,
        chuckwagon002x = 15,
        coach2 = 5,
        coach3 = 20,
        coach3_cutscene = 10,
        coach4 = 20,
        coach5 = 20,
        coach6 = 20,
        coal_wagon = 24,
        coalhopper01x = 1,
        gatchuck = 16,
        gatchuck_2 = 16,
        handcart = 2,
        huntercart01 = 6,
        keelboat = 5,
        logwagon = 5,
        logwagon2 = 5,
        midlandboxcar05x = 12,
        midlandrefrigeratorcar = 1,
        northcoalcar01x = 7,
        northflatcar01x = 3,
        northpassenger01x = 1,
        northpassenger03x = 1,
        northsteamer01x = 7,
        oilwagon01x = 14,
        oilwagon02x = 12,
        pirogue = 6,
        pirogue2 = 7,
        policewagon01x = 3,
        policewagongatling01x = 3,
        privatearmoured = 1,
        privatebaggage01x = 8,
        privateboxcar01x = 15,
        privateboxcar02x = 15,
        privateboxcar04x = 15,
        privatecoalcar01x = 3,
        privatedining01x = 2,
        privateflatcar01x = 3,
        privateobservationcar = 1,
        privateopensleeper01x = 3,
        privateopensleeper02x = 3,
        privatepassenger01x = 2,
        privaterooms01x = 2,
        privatesteamer01x = 2,
        rowboat = 7,
        rowboatswamp = 6,
        rowboatswamp02 = 6,
        ship_nbdguama2 = 2,
        skiff = 3,
        stagecoach001x = 4,
        stagecoach002x = 4,
        stagecoach003x = 4,
        stagecoach004_2x = 5,
        stagecoach004x = 3,
        stagecoach005x = 4,
        stagecoach006x = 7,
        supplywagon = 16,
        supplywagon2 = 16,
        trolley01x = 2,
        tugboat2 = 8,
        tugboat3 = 4,
        utilliwag = 17,
        wagon02x = 22,
        wagon03x = 16,
        wagon04x = 21,
        wagon05x = 20,
        wagon05x_2 = 20,
        wagon06x = 16,
        wagonarmoured01x = 31,
        wagoncircus01x = 1,
        wagoncircus02x = 1,
        wagondairy01x = 2,
        wagondoc01x = 1,
        wagonprison01x = 7,
        wagontraveller01x = 1,
        wagonwork01x = 2,
        warwagon2 = 6,
        wintercoalcar = 1,
    },
    extras = {
        armoredcar03x = { 5, 6, 7 },
        bountywagon01x = { 5 },
        caboose01x = { 1 },
        cart01 = { 1, 4 },
        cart05 = { 1, 2, 3 },
        cart07 = { 1 },
        cart08 = { 4 },
        chuckwagon000x = { 1, 2, 3 },
        chuckwagon002x = { 1, 2, 3 },
        coach2 = { 1, 2, 3, 5 },
        coalhopper01x = { 1, 2, 3, 4, 5 },
        gatchuck = { 1, 2, 3, 4 },
        gatchuck_2 = { 1 },
        horseboat = { 1, 2, 3, 4 },
        keelboat = { 5 },
        midlandboxcar05x = { 1, 2, 3, 4, 5 },
        midlandrefrigeratorcar = { 1, 2, 3 },
        northpassenger01x = { 1, 2, 3, 4, 5 },
        northpassenger03x = { 1, 2, 3, 4, 5 },
        policewagon01x = { 5 },
        privatebaggage01x = { 1, 2 },
        privateboxcar01x = { 1, 2, 3, 4, 5 },
        privateboxcar02x = { 1, 2, 3, 4, 5, 6, 7, 8, 9 },
        privateboxcar04x = { 5 },
        privatedining01x = { 1, 2, 3, 4, 5 },
        privateopensleeper01x = { 1, 2, 3 },
        privateopensleeper02x = { 1, 2, 3 },
        privatepassenger01x = { 1, 2, 3, 4, 5, 6 },
        rowboat = { 1 },
        rowboatswamp = { 5 },
        rowboatswamp02 = { 5 },
        ship_guama02 = { 1 },
        ship_nbdguama2 = { 1, 2, 3 },
        smuggler02 = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 },
        stagecoach001x = { 1, 2 },
        stagecoach002x = { 1, 2 },
        stagecoach004_2x = { 5, 6, 7 },
        stagecoach005x = { 1 },
        supplywagon = { 1, 2, 4 },
        trolley01x = { 1, 2 },
        tugboat2 = { 1, 2 },
        utilliwag = { 2 },
        wagon02x = { 1, 2, 3, 5 },
        wagon04x = { 1, 2, 3 },
        wagon05x = { 5 },
        wagon06x = { 1, 2 },
        wagoncircus01x = { 1 },
        wagoncircus02x = { 1 },
        wagondoc01x = { 1 },
    },
    propsets = {
        armoredcar01x = { "pg_veh_armoredCar01x_1" },
        armoredcar03x = { "pg_veh_armoredCar02x_1" },
        keelboat = { "pg_veh_keelboat_01", "pg_veh_keelboat_02", "pg_veh_keelboat_03" },
        boatsteam02x = { "pg_veh_boatsteam02x_1" },
        caboose01x = { "pg_veh_caboose01x_1" },
        canoe = { "pg_veh_canoe_01", "pg_veh_canoe_02" },
        cart01 = { "pg_re_checkpoint02x_food", "pg_re_moonshineCampgroupCart01x", "pg_teamster_cart01_breakables", "pg_teamster_cart01_gen", "pg_teamster_cart01_perishables", "pg_veh_cart01_1", "pg_veh_cart01_2", "pg_veh_cart01_3" },
        cart02 = { "pg_mission_caravanCart02x", "pg_teamster_cart02_breakables", "pg_teamster_cart02_gen", "pg_teamster_cart02_perishables" },
        cart03 = { "pg_delivery_Coal02x", "pg_mp_moonshinebiz_supplies01x_cart03", "pg_teamster_cart03_breakables", "pg_teamster_cart03_gen", "pg_teamster_cart03_perishables", "pg_veh_cart03_1", "pg_veh_cart03_2", "pg_veh_cart03_barrels01x" },
        cart04 = { "pg_mission_caravanCart04x", "pg_teamster_cart04_breakables", "pg_teamster_cart04_gen", "pg_teamster_cart04_perishables", "pg_veh_cart04_1", "pg_veh_cart04_2" },
        cart06 = { "pg_teamster_cart06_breakables", "pg_teamster_cart06_gen", "pg_teamster_cart06_perishables", "pg_veh_cart06_1", "pg_veh_cart06_2" },
        cart07 = { "pg_teamster_cart07_breakables", "pg_teamster_cart07_gen", "pg_teamster_cart07_perishables", "pg_veh_cart07_1", "pg_veh_cart07_2" },
        cart08 = { "pg_teamster_cart08_breakables", "pg_teamster_cart08_gen", "pg_teamster_cart08_perishables", "pg_veh_cart08_1", "pg_veh_cart08_2" },
        coach2 = { "pg_mission_mary3_01x", "pg_re_coachrobbery01x", "pg_veh_coach2_1", "pg_veh_coach2_bootA" },
        armysupplywagon = { "pg_rc_monroe1_01x" },
        chuckwagon000x = { "pg_re_fleeingfamily01x", "pg_teamster_chuckwagon000x_breakables", "pg_teamster_chuckwagon000x_gen", "pg_teamster_chuckwagon000x_perishables", "pg_veh_chuckwagon000x_1", "pg_veh_chuckwagon000x_2", "pg_veh_chuckwagon000x_3", "pg_veh_chuckwagon000x_2a", "pg_veh_chuckwagon000x_3a", "pg_veh_chuckwagon000x_4", "pg_veh_chuckwagon000x_orange_1", "pg_vehload_cotton01", "pg_vehload_crates01", "pg_vehload_haybale01", "pg_vehload_livestock01", "pg_vehload_lumber01", "pg_vehload_sacks01", "pg_vl_blacksmith01", "pg_vl_butcher01", "pg_vl_craftsman01", "pg_vl_delivery01", "pg_vl_farmer01", "pg_vl_farmer02", "pg_vl_ferrier01", "pg_vl_fisherman01", "pg_vl_hunter01", "pg_vl_movingFamily01", "pg_vl_rancher01", "pg_vl_rancher02", "pg_vl_rancher03", "pg_vl_rancher04", "pg_vl_rancher05", "pg_vl_tradesman01", "pg_vl_tradesman02", "pg_vl_tradesman03", "pg_vl_tradesman04", "pg_vl_travellingFamily01", "pg_vl_travellingLabour01" },
        supplywagon = { "pg_mission_cornwall1_01x", "pg_mp_moonshinebiz_supplies02x_supwag", "pg_teamster_supplywagon_breakables", "pg_teamster_supplywagon_gen", "pg_teamster_supplywagon_perishables", "pg_delivery_Cotton01x" },
        supplywagon2 = { "pg_mission_mud4_strauswag01x", "pg_mission_mud4_strauswag02x" },
        logwagon = { "pg_veh_logwagon_1" },
        logwagon2 = { "pg_veh_logwagon2_1" },
        coal_wagon = { "pg_delivery_Coal01x" },
        chuckwagon002x = { "pg_rc_exconfederates1_01x", "pg_teamster_chuckwagon002x_breakables", "pg_teamster_chuckwagon002x_gen", "pg_teamster_chuckwagon002x_perishables", "pg_veh_chuckwagon002x_1", "pg_veh_chuckwagon002x_2", "pg_veh_chuckwagon002x_3", "pg_vl_blacksmith01", "pg_vl_butcher01", "pg_vl_craftsman01", "pg_vl_delivery01", "pg_vl_farmer01", "pg_vl_farmer02", "pg_vl_ferrier01", "pg_vl_fisherman01", "pg_vl_hunter01", "pg_vl_movingFamily01", "pg_vl_rancher01", "pg_vl_rancher02", "pg_vl_rancher03", "pg_vl_rancher04", "pg_vl_rancher05", "pg_vl_tradesman01", "pg_vl_tradesman02", "pg_vl_tradesman03", "pg_vl_tradesman04", "pg_vl_travellingFamily01", "pg_vl_travellingLabour01" },
        handcart = { "pg_mission_trainrob3_01x" },
        horseboat = { "pg_veh_horseBoat_1", "pg_veh_horseBoat_1_wreckage" },
        pirogue = { "pg_veh_pirogue_01" },
        pirogue2 = { "pg_veh_pirogue_01" },
        ghosttraincaboose = { "pg_veh_caboose01x_1" },
        rowboat = { "pg_veh_rowboat_01", "pg_veh_rowboat_02", "pg_mp_veh_rowboat_supplies01", "pg_mp_veh_rowboat_supplies02", "pg_mp_veh_rowboat_supplies03", "pg_mp_veh_rowboat_supplies04" },
        rowboatswamp = { "pg_veh_rowboatswamp_01", "pg_veh_rowboatswamp_02", "pg_mp_veh_rowboatSwamp_supplies01", "pg_mp_veh_rowboatSwamp_supplies02", "pg_mp_veh_rowboatSwamp_supplies03", "pg_mp_veh_rowboatSwamp_supplies04" },
        rowboatswamp02 = { "pg_veh_rowboatswamp_01", "pg_veh_rowboatswamp_02" },
        ship_nbdguama = { "pg_veh_NBDguama_01x" },
        ship_nbdguama2 = { "pg_veh_shipNBDguama2_1" },
        stagecoach001x = { "pg_veh_stagecoach001x_1", "pg_veh_stagecoach001x_2" },
        stagecoach002x = { "pg_veh_stagecoach002x_1", "pg_veh_stagecoach002x_2", "pg_veh_stagecoach002x_bootA" },
        stagecoach003x = { "pg_veh_stagecoach003x_bootA" },
        stagecoach004x = { "pg_mission_utp2_coachLockbox", "pg_teamster_armourwag_breakables", "pg_teamster_armourwag_gen", "pg_teamster_armourwag_perishables" },
        stagecoach005x = { "pg_veh_stagecoach005x_1", "pg_veh_stagecoach005x_2" },
        stagecoach006x = { "pg_veh_stagecoach006x_1", "pg_veh_stagecoach006x_2" },
        trolley01x = { "pg_veh_trolley01x_1" },
        tugboat2 = { "pg_veh_tugboat2_1" },
        wagon02x = { "pg_gunforhire01x", "pg_vehload_cotton01", "pg_gunforhire02x", "pg_gunforhire03x", "Pg_Mis_Mud1_Wagon02x", "Pg_Mis_Mud1_Wagon02x_NoLooseProps", "pg_mission_ammoDeal", "pg_mission_caravanWagon02x", "pg_mission_marston7_lumber01x", "pg_mission_marston7_lumber02x", "pg_mission_marston7_lumber03x_doneloading", "pg_mission_mud1_wagon03x", "pg_mission_trainrob3_start01x", "pg_mission_weaponsDeal", "pg_mission_winter1_4thwagon01x", "pg_rc_BeauAndPene101x", "pg_rc_beauandpene201x", "pg_rc_forgiven601x", "pg_rc_nativewagoncornwall01x", "pg_rc_saddiesupplies00x", "pg_rc_saddiesupplies01x", "pg_re_armsdeal01x", "pg_re_odriscollwagon01x", "pg_re_supplydelivery_gsmith01x", "pg_re_supplyDelivery01x", "pg_re_trainholdup01x", "pg_sp_MarstonsWagon02x", "pg_teamster_wagon02x_breakables", "pg_teamster_wagon02x_gen", "pg_teamster_wagon02x_gen02", "pg_teamster_wagon02x_perishables", "pg_wagon02xClimbtest01x", "pg_mission_trainRob4_Wagon02x_dynamite", "pg_veh_wagon02x_1", "pg_veh_wagon02x_2", "pg_veh_wagon02x_3", "pg_vl_blacksmith01", "pg_vl_butcher01", "pg_vl_craftsman01", "pg_vl_delivery01", "pg_vl_farmer01", "pg_vl_farmer02", "pg_vl_ferrier01", "pg_vl_fisherman01", "pg_vl_hunter01", "pg_vl_movingFamily01", "pg_vl_rancher01", "pg_vl_rancher02", "pg_vl_rancher03", "pg_vl_rancher04", "pg_vl_rancher05", "pg_vl_tradesman01", "pg_vl_tradesman02", "pg_vl_tradesman03", "pg_vl_tradesman04", "pg_vl_travellingFamily01", "pg_vl_travellingLabour01" },
        wagon04x = { "pg_gunforhire01x", "pg_gunforhire02x", "pg_gunforhire03x", "pg_mission_caravanWagon04x", "pg_mission_mud1_jackwagon01x", "pg_mission_mud1_wagon01x", "pg_mission_mud1_wagon02x", "pg_mission_winter1_keiranWag01x", "pg_mission_winter1_wag04_01x", "pg_teamster_wagon04x_breakables", "pg_teamster_wagon04x_gen", "pg_teamster_wagon04x_gen02", "pg_teamster_wagon04x_perishables", "pg_veh_wagon04x_1", "pg_veh_wagon04x_2", "pg_veh_wagon04x_3", "pg_vl_blacksmith01", "pg_vl_butcher01", "pg_vl_craftsman01", "pg_vl_delivery01", "pg_vl_farmer01", "pg_vl_farmer02", "pg_vl_ferrier01", "pg_vl_fisherman01", "pg_vl_hunter01", "pg_vl_movingFamily01", "pg_vl_rancher01", "pg_vl_rancher02", "pg_vl_rancher03", "pg_vl_rancher04", "pg_vl_rancher05", "pg_vl_tradesman01", "pg_vl_tradesman02", "pg_vl_tradesman03", "pg_vl_tradesman04", "pg_vl_travellingFamily01", "pg_vl_travellingLabour01", "pg_veh_germFam_wagon04x_01" },
        wagon05x = { "pg_delivery_CKToil01x", "pg_delivery_Orange01x", "pg_gunforhire01x", "pg_gunforhire02x", "pg_gunforhire03x", "pg_ls_soldier2_01x", "pg_mission_bra1_wagon", "pg_mission_brt1_jump01x", "pg_mission_brt1_tomansion01x", "pg_mission_brt2", "pg_mission_BRT2_escape01x", "pg_mission_brt3", "pg_mission_caravanWagon05x", "pg_mission_moonshineSupplies", "pg_rc_ridethelightning01x", "pg_re_checkpoint01x", "pg_re_savagewagon01x", "pg_teamster_wagon05x_breakables", "pg_teamster_wagon05x_gen", "pg_teamster_wagon05x_perishables", "pg_veh_wagon05x_1", "pg_veh_wagon05x_2", "pg_veh_wagon05x_3", "pg_veh_wagon05x_4", "pg_veh_wagon05x_5", "pg_veh_wagon05x_cotton" },
        wagon06x = { "pg_teamster_wagon06x_breakables", "pg_teamster_wagon06x_gen", "pg_teamster_wagon06x_perishables", "pg_veh_wagon06x_1", "pg_veh_wagon06x_2", "pg_veh_wagon06x_3" },
        wagondairy01x = { "pg_delivery_dairy01x" },
        utilliwag = { "pg_cs_marston101x", "pg_mission_marston1_supplies01x", "pg_mission_marston1_supplies02x", "pg_mission_marston2_postoffice01x", "pg_mission_native2_01x", "pg_rc_dinoLady01x", "pg_teamster_utilitywag_breakables", "pg_teamster_utilitywag_gen", "pg_teamster_utilitywag_perishables", "pg_veh_utilliwag_1", "pg_veh_utilliwag_2", "pg_veh_utilliwag_3", "pg_veh_utilliwag_orange_1" },
        gatchuck = { "pg_mission_native2_01x", "pg_teamster_payroll01x_gat" },
        wagon05x_2 = { "pg_teamster_wagon05x_gen" },
        huntercart01 = { "pg_mp005_huntingWagonTarp01" },
        tugboat3 = { "pg_moonshiner3_tugboat2_1" },
    },
    lanterns = {
        keelboat = { "pg_veh_keelboat_lanterns_1" },
        cart01 = { "pg_teamster_cart01_lightupgrade1", "pg_teamster_cart01_lightupgrade2", "pg_teamster_cart01_lightupgrade3", "pg_veh_cart01_lanterns01" },
        cart06 = { "pg_re_deadbodies01x_lights", "pg_teamster_cart06_lightupgrade1", "pg_teamster_cart06_lightupgrade2", "pg_teamster_cart06_lightupgrade3", "pg_veh_cart06_lanterns01" },
        armysupplywagon = { "pg_veh_ArmySupplyWagon_lanterns01" },
        chuckwagon000x = { "pg_teamster_chuckwagon000x_lightupgrade1", "pg_teamster_chuckwagon000x_lightupgrade2", "pg_teamster_chuckwagon000x_lightupgrade3", "pg_veh_chuckwagon000x_lanterns" },
        coal_wagon = { "pg_teamster_coalwagon_lightupgrade1", "pg_teamster_coalwagon_lightupgrade2", "pg_teamster_coalwagon_lightupgrade3", "pg_veh_coal_wagon_lanterns01" },
        chuckwagon002x = { "pg_teamster_chuckwagon002x_lightupgrade1", "pg_teamster_chuckwagon002x_lightupgrade2", "pg_teamster_chuckwagon002x_lightupgrade3", "pg_veh_chuckwagon002x_lanterns01" },
        horseboat = { "pg_veh_horseboat_1_lights" },
        policewagon01x = { "pg_veh_policeWagon01x_lanterns01" },
        policewagongatling01x = { "pg_veh_policeWagonGatling01x_lanterns01" },
        rowboat = { "pg_veh_rowboat_lightupgrade_1", "pg_veh_rowboat_lightupgrade_2", "pg_veh_rowboat_lightupgrade_3" },
        ship_guama02 = { "pg_veh_shipguama02_lights01x" },
        turbineboat = { "pg_veh_turbineboat01x_lights" },
        ship_nbdguama = { "pg_veh_nbdguama_lights01x" },
        ship_nbdguama2 = { "pg_veh_shipnbdguama2_1_lights" },
        stagecoach003x = { "pg_veh_stagecoach003x_lanterns01" },
        trolley01x = { "pg_veh_trolley01x_lights" },
        tugboat2 = { "pg_veh_tugboat2_lights01x" },
        wagon02x = { "pg_teamster_wagon02x_lightupgrade1", "pg_teamster_wagon02x_lightupgrade2", "pg_teamster_wagon02x_lightupgrade3", "pg_veh_wagon02x_lanterns01", "pg_veh_wagonsuffrage_lanterns01" },
        wagon04x = { "pg_teamster_wagon04x_lightupgrade1", "pg_teamster_wagon04x_lightupgrade2", "pg_teamster_wagon04x_lightupgrade3", "pg_veh_wagon04x_lanterns01" },
        wagon05x = { "pg_teamster_wagon05x_lightupgrade1", "pg_teamster_wagon05x_lightupgrade2", "pg_teamster_wagon05x_lightupgrade3", "pg_veh_wagon05x_2_lanterns01", "pg_veh_wagon05x_lanterns01", "pg_veh_wagon05x_lanterns02" },
        wagon06x = { "pg_teamster_wagon06x_lightupgrade1", "pg_teamster_wagon06x_lightupgrade2", "pg_teamster_wagon06x_lightupgrade3" },
        wagonprison01x = { "pg_veh_wagonPrison01x_lanterns01" },
        utilliwag = { "pg_veh_utilliwag_lightupgrade_1", "pg_veh_utilliwag_lightupgrade_2", "pg_veh_utilliwag_lightupgrade_3", "pg_veh_utilliwag_lanterns01" },
        gatchuck = { "pg_teamster_gatchuck_lightupgrade1", "pg_teamster_gatchuck_lightupgrade2", "pg_teamster_gatchuck_lightupgrade3", "pg_veh_gatchuck_lanterns01" },
        bountywagon01x = { "pg_teamster_chuckwagon002x_lightupgrade1", "pg_teamster_chuckwagon002x_lightupgrade2", "pg_teamster_chuckwagon002x_lightupgrade3", "pg_veh_chuckwagon002x_lanterns01" },
        wagonarmoured01x = { "pg_veh_wagonarmoured01x_lanterns01" },
        huntercart01 = { "pg_re_deadbodies01x_lights", "pg_teamster_cart06_lightupgrade1", "pg_teamster_cart06_lightupgrade2", "pg_teamster_cart06_lightupgrade3", "pg_veh_cart06_lanterns01" },
        tugboat3 = { "pg_veh_tugboat2_lights01x" },
    },
}
